
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird tb_monitoring - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
    jobs:
      cd:  # deploy changes to workspace 'tb_monitoring'
        uses: tinybirdco/ci/.github/workflows/cd.yml@v4.1.0
        with:
          data_project_dir: .
        secrets:
          tb_admin_token: ${{ secrets.TB_MONITORING_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
